### PR TITLE
Do not add .js extension to entries values

### LINKED ISSUE #165: Can't use the new slsw.lib.entries with typescript
# This is a Bug Report

## Description

`slsw.lib.entries` returns an object with keys `name.js`, and as values the string `./name.js`.
This is making developing with typescript quite difficult:
1. The key shouldn't have an extension in case i'm using an output name like `[name].[hash].js`, or in case I actually want a different extension.
2. The value should't have an extension as well, so I can actually input typescript files

## Additional Data

* ***Serverless-Webpack Version you're using***: 2.1.0

### PR DESCRIPTION
**Pull request by kikar**
## What did you implement:

Closes #165 

## Todos:

- Write tests
- [x] Write documentation
- Fix linting errors (not yet implemented)
- Make sure code coverage hasn't dropped (not yet implemented)
- Provide verification config / commands / resources
- Enable "Allow edits from maintainers" for this PR
- Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/validate.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ const _ = require('lodash');
 
 function getEntryForFunction(serverlessFunction) {
 	const handler = serverlessFunction.handler;
-	const handlerFile = /(.*)\..*?$/.exec(handler)[1] + '.js';
+	const handlerFile = /(.*)\..*?$/.exec(handler)[1];
```
Comment (HyperBrain) [inline lib/validate.js]: We should actually retrieve the correct file extension here and set it in the value of the key, so that there's no need to use custom code in the webpack configuration to get the plugin running.

```
function getHandlerFileExtension(baseName) {
  // Use fs/fs-extra/path or any other appropriate mechanism to determine the actual file extension of the handler
  // Maybe we can search for known and supported endings in a predefined order
  // So that the standard extension 'js' is preferred if, by accident, there are multiple copies
  // of the handler with different extensions - or throw an error in that case.
  const allowedExtensions = [
    'js', 'ts', 'jsx'
  ];
  const handlerExtension = ...;
  ...
  return handlerExtension;
}
...
const handlerFileBaseName = /(.*)\..*?$/.exec(handler)[1];
const handerFile = `${handlerFileBaseName}.${getHandlerFileExtension(handlerFileBaseName)}`;
...
return {
  [handlerFileBaseName]: `./${handlerFile}`
};
```

File: tests/validate.test.js [hunk 2]
```diff
@@ -277,10 +277,10 @@ describe('validate', () => {
         .then(() => {
           const lib = require('../lib/index');
           const expectedLibEntries = {
-            'module1.js': './module1.js',
-            'module2.js': './module2.js',
-            'handlers/func3/module2.js': './handlers/func3/module2.js',
-            'handlers/module2/func3/module2.js': './handlers/module2/func3/module2.js',
+            'module1': './module1',
```
Comment (HyperBrain) [inline tests/validate.test.js]: The tests have to be adapted AFTER the changes above, because the used external functions to determine the extension have to be stubbed with sinon.

**Comment by HyperBrain** [comment]
Dtermining the extension will also support the case where single functions in a project are updated and the used extension changes. E.g. if you change a function from js to jsx or from js to ts. Then the next deploy will just work out of the box because your config file does not need to know anything about the specific function configurations.

File: lib/validate.js (hunk 1 above)
Comment (kikar) [inline lib/validate.js]: Do we assume all the function files are in the servicePath folder?

Comment (HyperBrain) [inline lib/validate.js]: At least somewhere under the servicePath. The handlerBaseName contains the path elements relative to the handler. So, for example, it could be `handlers/shop/order/handler`, but we can assume that handler files are never outside the service folder (of course the user can use symlinks to access files outside the service directory, but checking if the baseName + extension exists, will automatically reveil the correct results in this case)

Comment (HyperBrain) [inline lib/validate.js]: Better rename the `handlerFileBaseName` variable to `handlerFilePathWithBaseName` as it actually contains the path + the basename.

**Comment by kikar** [comment]
Latest commit should do the job. Problem is that all tests fail cause we don't actually have files to check

File: lib/validate.js [hunk 3]
```diff
@@ -27,13 +49,14 @@ module.exports = {
 		// Expose entries - must be done before requiring the webpack configuration
     const entries = {};
     const functions = this.serverless.service.getAllFunctions();
+    const allFilesInServicePath = listFiles(this.serverless.config.servicePath);
```
Comment (HyperBrain) [inline lib/validate.js]: Is it necessary to browse the whole service dir file tree here? I think that is very expensive - the directory might include node_modules etc.

Assuming that the handlers we have already point to the handler files we check, we know exactly where the files have to be. So just searching in getEntryExtension(handlerFile) for `handlerFile.*` should retrieve the full file automatically (and even shows us if it is ambiguous, which is an error on the user side if multiple of our allowed extensions are found). We do not need to be aware of the complete file hierarchy here.

**Comment by HyperBrain** [comment]
I can take care of the unit tests as soon as we have a performant and working solution.

**Comment by kikar** [comment]
Improved the file search as recommended

File: lib/validate.js [hunk 4]
```diff
@@ -3,16 +3,24 @@
 const BbPromise = require('bluebird');
 const path = require('path');
 const fse = require('fs-extra');
+const glob = require('glob');
 const lib = require('./index');
 const _ = require('lodash');
 
-function getEntryForFunction(serverlessFunction) {
+function getEntryExtension(fileName, servicePath) {
+  let files = glob.sync(`${fileName}.*`, { cwd: servicePath });
```
Comment (HyperBrain) [inline lib/validate.js]: can be `const`

File: lib/validate.js [hunk 5]
```diff
@@ -3,16 +3,24 @@
...
+  return path.extname(files[0]);
```
Comment (HyperBrain) [inline lib/validate.js]: We could emit a warning in case more than one file is found here:
```
if (_.size(files) > 1) {
  this.serverless.cli.log(`WARNING: More than one matching handlers found for ${fileName}. Using ${_.first(files)}.`);
}
```

Of course the now global function(s) have to be moved into validate() to have access to the correct `this`.

Also use `_.first(files)` here instead of `files[0]` as the lodash variant will not crash if no file is found.

**Comment by HyperBrain** [comment]
I will add the unit tests and the doc/example updates tomorrow, so that we can release 2.2.0 also tomorrow.

**Comment by HyperBrain** [comment]
I tested it with one of our projects. That worked nicely. Also rebased onto the current webpack master.
Should be everything ok now. The only thing that can happen is, that if there are unrelated files besides the handler, that just have a different ending, the glob could match them (e.g. `handler.doc`). However it will show the warning we implemented.

If that turns out to be a problem later, we can restrict the allowed extensions by setting the glob pattern to `${fileName}.@(js|ts|jsx)`.

**Comment by HyperBrain** [comment]
Just added some more complex test cases and a preference sorting. I will do some final tests now.
For most standard uses of lib.entries it should work now - if someone needs more sophisticated handling he can program the complete stuff in his webpack.conf - thanks to the serverless and option exports.
